# Generated by Django 3.1.2 on 2020-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20201102_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passangers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passangers', to='flights.Flight')),
            ],
        ),
    ]
