# Generated by Django 3.1.2 on 2020-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passangers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flights.Flight'),
        ),
    ]
