# Generated by Django 3.1.2 on 2020-11-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20201118_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passangers',
            new_name='Passenger',
        ),
    ]
