# Generated by Django 3.1.2 on 2020-11-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20201118_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
